SET LINESIZE 200
SET PAGESIZE 100
COLUMN trigger_name FORMAT A30

SELECT trigger_name, status
FROM   user_triggers
WHERE  trigger_name IN (
  'TRG_AUDIT_STATUS_CHANGE',
  'TRG_AUDIT_LOAN_STATUS',
  'TRG_PREVENT_SR_MODIFICATION',
  'TRG_AUDIT_ACCOUNT_WRITE',
  'TRG_AUDIT_KYC_CHANGE',
  'TRG_AUDIT_TRANSACTION',
  'TRG_AUDIT_DUAL_APPROVAL'
)
ORDER BY trigger_name;
EXIT;
