-- Table to store OTPs for verification, recreated for secure transactions
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE OTPS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE OTPS (
    otp_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id RAW(16) NOT NULL,
    transaction_id VARCHAR2(100),
    otp_hash VARCHAR2(255) NOT NULL,
    purpose VARCHAR2(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    attempts NUMBER DEFAULT 0,
    status VARCHAR2(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED')),
    CONSTRAINT fk_otp_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
);

COMMIT;
