const oracledb = require('oracledb');
require('dotenv').config();

async function run() {
    let connection;
    try {
        connection = await oracledb.getConnection({
            user: process.env.DB_USER,
            password: process.env.DB_PASSWORD,
            connectString: process.env.DB_CONNECTION_STRING
        });

        console.log('Adding session_token to USERS...');
        try {
            await connection.execute("ALTER TABLE USERS ADD (session_token VARCHAR2(255))");
            console.log('session_token added.');
        } catch (e) {
            if (e.message.includes('ORA-01430')) {
                console.log('session_token already exists.');
            } else {
                console.error('Error adding session_token:', e.message);
            }
        }

        console.log('Dropping old OTPS table...');
        try {
            await connection.execute('DROP TABLE OTPS CASCADE CONSTRAINTS');
        } catch (e) {
            if (!e.message.includes('ORA-00942')) {
                console.error('Error dropping OTPS:', e.message);
            }
        }

        console.log('Creating new OTPS table...');
        await connection.execute(`
        CREATE TABLE OTPS (
            otp_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id RAW(16) NOT NULL,
            transaction_id VARCHAR2(100),
            otp_hash VARCHAR2(255) NOT NULL,
            purpose VARCHAR2(50) NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            expires_at TIMESTAMP NOT NULL,
            attempts NUMBER DEFAULT 0,
            status VARCHAR2(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED')),
            CONSTRAINT fk_otp_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
        )
    `);
        console.log('OTPS table recreated successfully.');

    } catch (err) {
        console.error(err);
    } finally {
        if (connection) {
            try { await connection.close(); } catch (e) { console.error(e); }
        }
    }
}

run();
